# Generated by Django 5.1.3 on 2024-11-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roombooking",
            name="booked_by",
        ),
        migrations.AddField(
            model_name="roombooking",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="roombooking",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="roombooking",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="roombooking",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
