# Generated by Django 5.1.3 on 2024-11-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_roombooking_booked_by_roombooking_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roombooking",
            name="night_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roombooking",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
